Bug fix: Arc DNS injector breaks on Java 17
Error:
Failed to inject cache!
java.lang.reflect.InaccessibleObjectException: Unable to make java.net.InetAddress$CachedAddresses(java.lang.String,java.net.InetAddress[],long) accessible: module java.base does not "opens java.net" to unnamed module @4157f54e