Add Java sandbox switch, for Quilt installer #3113 #3187
The security manager malfunctions, causing access denial of certain operations. While this isn't actually a solution, it should at least allow Quilt installer to proceed.
java.util.concurrent.CompletionException: java.security.AccessControlException: access denied ("java.net.SocketPermission" "meta.fabricmc.net:443" "connect,resolve")